export const metadata = {
  title: 'About us!',
  description: 'Generated by create next app',
}

export default function AboutUsLayout({ children }) {
  return (
    <section>
      {children}
    </section>
  )
}
